### ISSUE TITLE
stop monthly tweet downloads?

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/ropensci-tweets#6]
@maelle Now that Twitter allows folks to access/ download past tweets, should I stop doing monthly d/l of rOpenSci tweets? We've never used them for anything but I originally thought it was valuable to have info on RTs etc.

I would continue to grab a few monthly metrics like followers, mentions etc.

2) Should I delete all past months of data files like `tweet_activity_metrics_rOpenSci_20161201_20170101_en.csv`?

**Comment by maelle** [comment]
@stefaniebutland How does Twitter allow that? Wouldn't one still need to export the data month by month (i.e. 6 months, each month in a csv)?

Or is an API thing?

**Comment by stefaniebutland** [comment]
See https://help.twitter.com/en/managing-your-account/how-to-download-your-twitter-archive

I interpret that to mean we can get all past tweets. What might not give us is # of RTs of a tweet, URL clicks etc in that month of data, however, we have not used this info in the past. I'll bring this up a a staff mtg to decide.

**Comment by maelle** [comment]
I've requested the archive for my own Twitter account so we can now for sure what's included. I'll update this thread then.

Good idea to discuss in a future staff meeting.

**Comment by maelle** [comment]
In the archive there is a file called tweet.js and it has the number of likes/tweets, but not more precise analytics (e.g. not even the number of quote retweets).

**Comment by stefaniebutland** [comment]
I'll keep downloading monthly. Does not take much time
